### ISSUE TITLE
[REQUEST] kindly add nethunter.defconfig for veux 🙏

### ISSUE THREAD

**Issue by mahrabshaon** [dereference23/kernel_xiaomi_sm6375#2] opened 2023-12-12 07:54 UTC
Sir, Can you please add nethunter defconfig for using HID, WIRELESS CARD, RF etc?
Thanks in advance.

**Comment by dereference23** [comment] 2023-12-12 07:57
Duplicate of #1

**Closed as completed by dereference23** 2023-12-12 07:57 UTC
